_TRADE_CONDITIONS = {
    0: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    1: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    2: {
        'cancel': False,
        'latereport': True,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': False,
    },
    4: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    5: {
        'cancel': False,
        'latereport': True,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': False,
    },
    6: {
        'cancel': False,
        'latereport': True,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': False,
    },
    7: {
        'cancel': False,
        'latereport': True,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    8: {
        'cancel': False,
        'latereport': True,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': False,
    },
    9: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    10: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    11: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    12: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    13: {
        'cancel': False,
        'latereport': True,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': False,
    },
    14: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    15: {
        'cancel': False,
        'latereport': True,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': False,
    },
    16: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    17: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': False,
    },
    18: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': True,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    19: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    20: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    21: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    22: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    25: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    26: {
        'cancel': False,
        'latereport': True,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    27: {
        'cancel': False,
        'latereport': True,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    28: {
        'cancel': False,
        'latereport': True,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    29: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    30: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    31: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    32: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    33: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    34: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    35: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    36: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    37: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    38: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    39: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    40: {
        'cancel': True,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    41: {
        'cancel': True,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    42: {
        'cancel': True,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    43: {
        'cancel': True,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    44: {
        'cancel': True,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    45: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    46: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    47: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    48: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    49: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    50: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    51: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    52: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    53: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    54: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    55: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    56: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': True,
        'low': True,
        'last': True,
    },
    58: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    59: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    60: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    61: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    62: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': False,
    },
    63: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    64: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    65: {
        'cancel': False,
        'latereport': True,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    66: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    67: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    68: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': True,
        'low': True,
        'last': False,
    },
    69: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': True,
        'low': True,
        'last': False,
    },
    70: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    71: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    72: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    73: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    74: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    75: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    76: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    77: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    78: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    79: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    80: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    81: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    82: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    83: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    84: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': True,
        'low': False,
        'last': False,
    },
    85: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': True,
        'last': False,
    },
    86: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    87: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    88: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    89: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    90: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    91: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    92: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    93: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    94: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    95: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    96: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': False,
    },
    97: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    98: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': False,
    },
    99: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': False,
    },
    100: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    101: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': False,
    },
    102: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': False,
    },
    103: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    104: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    105: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    106: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': False,
    },
    107: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': True,
    },
    108: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    109: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    110: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    111: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    112: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    113: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    114: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    115: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    116: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    117: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': True,
        'low': True,
        'last': True,
    },
    118: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    119: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    120: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    121: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    122: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    123: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': False,
        'high': False,
        'low': False,
        'last': False,
    },
    124: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    125: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    126: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    127: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    128: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    129: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    130: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    131: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    132: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    133: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    134: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    135: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    136: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    137: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    138: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    139: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    140: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    141: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    142: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    143: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    144: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    145: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    146: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': True,
        'low': True,
        'last': True,
    },
    147: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
    148: {
        'cancel': False,
        'latereport': False,
        'autoexecuted': False,
        'volume': True,
        'high': False,
        'low': False,
        'last': False,
    },
}
